# -*- coding: utf-8 -*-
"""proje1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8irUhk3Kism44XmSN69GTFMJrUbhNp2
"""

import pandas as pd

# Titanic veri setini yükleme
df = pd.read_csv('/content/drive/MyDrive/phyton/train.csv')

# İlk birkaç satırı görüntüleme
df.head()

# Eksik değerlerin kontrolü
df.isnull().sum()

# Eksik değerleri doldurma
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin'], inplace=True)

# Veri türlerini dönüştürme
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

# Temel istatistikler
df.describe()

# Cinsiyet ve hayatta kalma oranı arasındaki ilişki
survival_rate_by_gender = df.groupby('Sex')['Survived'].mean()
print(survival_rate_by_gender)

# Matplotlib ve Seaborn kullanarak görselleştirme
import matplotlib.pyplot as plt
import seaborn as sns

# Hayatta kalma oranının cinsiyete göre dağılımı
sns.barplot(x='Sex', y='Survived', data=df)
plt.title('Cinsiyete Göre Hayatta Kalma Oranı')
plt.xlabel('Cinsiyet')
plt.ylabel('Hayatta Kalma Oranı')
plt.show()

# Yaş dağılımı ve hayatta kalma oranı
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='Age', hue='Survived', multiple='stack')
plt.title('Yaş Dağılımı ve Hayatta Kalma Oranı')
plt.xlabel('Yaş')
plt.ylabel('Yolcu Sayısı')
plt.show()

# Sadece sayısal sütunları seçme
numeric_df = df.select_dtypes(include='number')

# Ortalama değeri en yüksek olan sütunu bulma
mean_values = numeric_df.mean()  # Tüm sayısal sütunların ortalamalarını hesapla
max_mean_column = mean_values.idxmax()  # En yüksek ortalama değeri olan sütunun adını bul
max_mean_value = mean_values.max()  # En yüksek ortalama değeri bul

print(f"Ortalama değeri en yüksek olan sütun: {max_mean_column}, Değer: {max_mean_value}")

